#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef IRLIBSWIFT_SWIFT_H
#define IRLIBSWIFT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Realm;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IrLibSwift",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIBarButtonItem;

SWIFT_PROTOCOL("_TtP10IrLibSwift16BarButtonShowing_")
@protocol BarButtonShowing
- (void)addBarButton:(UIBarButtonItem * _Nonnull)button;
@end




SWIFT_CLASS("_TtC10IrLibSwift18IRAuthInfoProvider")
@interface IRAuthInfoProvider : NSObject
@property (nonatomic, copy) NSString * _Nonnull userToken;
@property (nonatomic, copy) NSString * _Nonnull basePath;
@property (nonatomic, copy) NSString * _Nonnull domain;
@property (nonatomic) BOOL isMultiportal;
- (nonnull instancetype)initWithUserToken:(NSString * _Nonnull)userToken basePath:(NSString * _Nonnull)basePath domain:(NSString * _Nonnull)domain isMultiportal:(BOOL)isMultiportal OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RLMRealmConfiguration;
@class NSNumber;

SWIFT_PROTOCOL("_TtP10IrLibSwift26IRDataBaseSettingsProvider_")
@protocol IRDataBaseSettingsProvider
@property (nonatomic, readonly, strong) RLMRealmConfiguration * _Nonnull realmConfig;
@property (nonatomic, readonly, strong) NSNumber * _Nullable previousDbVersion;
@end

@class NSError;
@class Photo;
@class IRDataManagerSettings;
@class Visit;
@class VisitWidgetMatrix;
@class VisitWidgetMacroCategory;
@class VisitWidgetTasksData;

SWIFT_PROTOCOL("_TtP10IrLibSwift21IRDataManagerProtocol_")
@protocol IRDataManagerProtocol
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)clearStoresLoadDate;
- (BOOL)createVisitWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId error:(NSError * _Nullable * _Nullable)error;
- (void)sendCurrentVisit;
- (void)fetchRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)sendPhotoWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Photo *> * _Nonnull)photosReadyToSendWithVisitId:(NSString * _Nullable)visitId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)recognitionResultRecivedCompletelyForPhotoWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Photo *> * _Nonnull)photosWithNoRecognitionResult SWIFT_WARN_UNUSED_RESULT;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)updateCurrentUserWithName:(NSString * _Nonnull)name externalId:(NSString * _Nonnull)externalId;
- (void)updateSettingsFrom:(IRDataManagerSettings * _Nonnull)settings;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Visit *> * _Nonnull)visitsWithNoWidgets SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)defaultMatrixFromVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMacroCategory *> * _Nullable)widgetMacroCategoriesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nullable)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)widgetMatrixForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMatrix *> * _Nullable)widgetMatricesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetTasksData *> * _Nullable)widgetTasksForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType SWIFT_WARN_UNUSED_RESULT;
- (void)updateProductForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId macroCategoryId:(NSString * _Nonnull)macroCategoryId productId:(NSString * _Nonnull)productId reasonId:(NSInteger)reasonId comment:(NSString * _Nullable)comment;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitsWithLimit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)downloadPhotosForPreviousVisitsWithVisitId:(NSString * _Nullable)visitId limit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (void)addSendSceneBlockToSequenceWithSceneId:(NSString * _Nonnull)sceneId block:(void (^ _Nonnull)(void))block;
- (void)restartSendPhotoSequenceWithResetAttemptIntervals:(BOOL)resetAttemptIntervals completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)deletePhotoWithId:(NSString * _Nonnull)id;
- (void)cancelRequests;
@end


SWIFT_CLASS("_TtC10IrLibSwift13IRDataManager")
@interface IRDataManager : NSObject <IRDataManagerProtocol>
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
+ (void)updateAppInfoWithIsApp:(BOOL)isApp;
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)clearStoresLoadDate;
- (BOOL)createVisitWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId error:(NSError * _Nullable * _Nullable)error;
- (void)sendCurrentVisit;
- (void)fetchRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)restartSendPhotoSequenceWithResetAttemptIntervals:(BOOL)resetAttemptIntervals completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)sendPhotoWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Взаимодействие с новым классом Photo
- (NSArray<Photo *> * _Nonnull)photosReadyToSendWithVisitId:(NSString * _Nullable)visitId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)recognitionResultRecivedCompletelyForPhotoWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Photo *> * _Nonnull)photosWithNoRecognitionResult SWIFT_WARN_UNUSED_RESULT;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
/// Обновление выбранной торговой точки. Используется в случае работы с либой / через диплинки.
/// \param storeId идентификатор торговой точки
///
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)updateCurrentUserWithName:(NSString * _Nonnull)name externalId:(NSString * _Nonnull)externalId;
- (void)updateSettingsFrom:(IRDataManagerSettings * _Nonnull)settings;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Visit *> * _Nonnull)visitsWithNoWidgets SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)defaultMatrixFromVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMacroCategory *> * _Nullable)widgetMacroCategoriesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nullable)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)widgetMatrixForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMatrix *> * _Nullable)widgetMatricesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetTasksData *> * _Nullable)widgetTasksForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType SWIFT_WARN_UNUSED_RESULT;
- (void)updateProductForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId macroCategoryId:(NSString * _Nonnull)macroCategoryId productId:(NSString * _Nonnull)productId reasonId:(NSInteger)reasonId comment:(NSString * _Nullable)comment;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSInteger)cachedTasksCount SWIFT_WARN_UNUSED_RESULT;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitsWithLimit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)downloadPhotosForPreviousVisitsWithVisitId:(NSString * _Nullable)visitId limit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (void)addSendSceneBlockToSequenceWithSceneId:(NSString * _Nonnull)sceneId block:(void (^ _Nonnull)(void))block;
- (void)deletePhotoWithId:(NSString * _Nonnull)id;
- (void)cancelRequests;
- (NSInteger)saveStoreWithExternalId:(NSString * _Nonnull)externalId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class IRSharedSettings;

/// Класс для настройки IRDataManager.
SWIFT_CLASS("_TtC10IrLibSwift21IRDataManagerSettings")
@interface IRDataManagerSettings : NSObject
- (nonnull instancetype)initWithAuthInfoProvider:(IRAuthInfoProvider * _Nonnull)authInfoProvider dbSettingsProvider:(id <IRDataBaseSettingsProvider> _Nonnull)dbSettingsProvider sharedSettings:(IRSharedSettings * _Nonnull)sharedSettings installId:(NSString * _Nonnull)installId notificationPrefix:(NSString * _Nullable)notificationPrefix OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum IRLocationErrorBlockType : NSInteger;

/// Настройки запретов на съёмку в зависимости от геолокации
SWIFT_CLASS("_TtC10IrLibSwift32IRGeolocationErrorSharedSettings")
@interface IRGeolocationErrorSharedSettings : NSObject
@property (nonatomic) enum IRLocationErrorBlockType type;
@property (nonatomic) NSInteger threshold;
- (nonnull instancetype)initWithType:(enum IRLocationErrorBlockType)type threshold:(NSInteger)threshold OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IRLocationErrorBlockType, closed) {
  IRLocationErrorBlockTypeNone = 0,
  IRLocationErrorBlockTypeFull = 1,
  IRLocationErrorBlockTypePartial = 2,
};

typedef SWIFT_ENUM(NSInteger, IRNetworkError, closed) {
  IRNetworkErrorNoConnection = 503,
  IRNetworkErrorAuthError = 403,
  IRNetworkErrorProcessing = 202,
  IRNetworkErrorServerError = 500,
  IRNetworkErrorDecodeError = 901,
  IRNetworkErrorEncodeError = 902,
  IRNetworkErrorResponseDecodeError = 903,
  IRNetworkErrorUnknown = -1,
};

@protocol StoresModuleOutput;
@class UIViewController;

SWIFT_CLASS("_TtC10IrLibSwift19IRNewScreensBuilder")
@interface IRNewScreensBuilder : NSObject
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nonnull)storesScreenWithOutput:(id <StoresModuleOutput> _Nonnull)output SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift14IRNotification")
@interface IRNotification : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull authErrorNotification;)
+ (NSNotificationName _Nonnull)authErrorNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRPhotoApproveMode, closed) {
  IRPhotoApproveModeManual = 0,
  IRPhotoApproveModeAutomatic = 1,
};

@class IRStoresSharedSettings;

/// Группа классов ответственная за общие настройки библиотеки, получаемые с сервера в запросе getSettings.
/// Временное решение для передачи необходимых настроек из старой либы в новую. Позже запрос на getSettings будет вынесен в эту либу.
SWIFT_CLASS("_TtC10IrLibSwift16IRSharedSettings")
@interface IRSharedSettings : NSObject
@property (nonatomic, readonly, strong) IRStoresSharedSettings * _Nullable storesSettings;
@property (nonatomic, readonly, strong) IRGeolocationErrorSharedSettings * _Nonnull locationError;
@property (nonatomic, readonly) enum IRPhotoApproveMode photoApproveMode;
@property (nonatomic, readonly) BOOL shouldSyncManually;
- (nonnull instancetype)initWithStoresSettings:(IRStoresSharedSettings * _Nonnull)storesSettings locationError:(IRGeolocationErrorSharedSettings * _Nonnull)locationError photoApproveMode:(enum IRPhotoApproveMode)photoApproveMode shouldSyncManually:(BOOL)shouldSyncManually OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift27IRStoredClassesInfoProvider")
@interface IRStoredClassesInfoProvider : NSObject
+ (NSArray * _Nonnull)storedClasses SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class IRStoredStateSettingsVisit;
@class IRStoredStateSettingsStore;

/// Хранимые настройки текущего состояния - идентификаторы текущего визита, торговой точки и тому подобное.
/// Ojbc-библиотека использует этот класс для получения и обновления актуальных данных.
SWIFT_CLASS("_TtC10IrLibSwift21IRStoredStateSettings")
@interface IRStoredStateSettings : NSObject
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) IRStoredStateSettingsVisit * _Nullable currentVisit;
@property (nonatomic, readonly, strong) IRStoredStateSettingsStore * _Nullable currentStore;
- (void)clearCurrentVisit;
- (void)updateCurrentStoreId:(NSInteger)storeId;
- (void)updateCurrentExternalStoreId:(NSString * _Nonnull)externalStoreId;
- (void)updateCurrentUserWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name externalId:(NSString * _Nullable)externalId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsStore")
@interface IRStoredStateSettingsStore : NSObject
@property (nonatomic, readonly) NSInteger storeId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsVisit")
@interface IRStoredStateSettingsVisit : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull visitId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalVisitId;
@property (nonatomic, readonly, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nullable externalUserId;
@property (nonatomic, readonly, copy) NSString * _Nonnull startTimestamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift22IRStoresSharedSettings")
@interface IRStoresSharedSettings : NSObject
@property (nonatomic, strong) NSNumber * _Nullable forceUpdateInterval;
- (nonnull instancetype)initWithForceUpdateInterval:(NSNumber * _Nullable)forceUpdateInterval OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class RecognitionResultRealogram;
@class RecognitionResultActualAssortment;

SWIFT_CLASS("_TtC10IrLibSwift5Photo")
@interface Photo : RLMObject
@property (nonatomic, copy) NSString * _Nonnull photoId;
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nullable externalVisitId;
@property (nonatomic, copy) NSString * _Nonnull sceneId;
@property (nonatomic) NSInteger sceneTypeId;
@property (nonatomic, copy) NSString * _Nonnull sceneTypeName;
@property (nonatomic, copy) NSString * _Nullable taskId;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSDate * _Nullable createdTime;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
/// Скачано ли это фото с портала
@property (nonatomic) BOOL isDownloaded;
/// Скачано ли изображение для этого фото
@property (nonatomic) BOOL isImageDownloaded;
@property (nonatomic) NSInteger state;
@property (nonatomic) NSInteger sceneNumber;
@property (nonatomic) NSInteger photoNumber;
@property (nonatomic) NSInteger innerNumber;
@property (nonatomic) NSInteger maxNumber;
/// Результат анализа
@property (nonatomic) NSInteger blur;
@property (nonatomic) BOOL isQualityError;
@property (nonatomic) BOOL isGeolocationError;
@property (nonatomic) BOOL isTiltAngleError;
@property (nonatomic) BOOL isApproved;
@property (nonatomic) BOOL isSelected;
@property (nonatomic) BOOL isSceneClosed;
/// Ошибки
@property (nonatomic) NSInteger errorState;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
/// Отправка на сервер и получение результата
@property (nonatomic) NSInteger sendPhotoAttemptsCounter;
@property (nonatomic) NSInteger timeNextAttemptToSendPhoto;
/// Время следующей попытки отправить фото
@property (nonatomic) NSInteger recognitionResultAttemptsCounter;
@property (nonatomic) NSInteger timeNextAttemptToRecognitionResult;
/// Время следующей попытки отправить запрос отчета
/// Результаты распознования
@property (nonatomic, strong) RLMArray<RecognitionResultRealogram *> * _Nonnull realogram;
@property (nonatomic, strong) RLMArray<RecognitionResultActualAssortment *> * _Nonnull actualAssortment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Новые типы можно добавлять только в конец, так как порядок имеет значение. Перемешивать после публикации новой версии тоже не стоит
/// В objC вызов вида IRPhotoStateВeleted
typedef SWIFT_ENUM(NSInteger, IRPhotoState, closed) {
  IRPhotoStateDeleted = 1,
  IRPhotoStateNotReadyToSend = 2,
  IRPhotoStateReadyToSend = 3,
  IRPhotoStateNotStitched = 4,
  IRPhotoStateNotAnalysed = 5,
  IRPhotoStateNotSaved = 6,
  IRPhotoStateSent = 7,
  IRPhotoStateFinished = 8,
};

/// Статусы ошибок, пока они нужны так как старая логика сильно завязана, в дальнейшем можно будет перенести ошибки в IRPhotoState как статус отправки
typedef SWIFT_ENUM(NSInteger, IRPhotoErrorState, closed) {
  IRPhotoErrorStateNoError = 1,
  IRPhotoErrorStateAnalyseError = 2,
  IRPhotoErrorStateStitcherError = 3,
  IRPhotoErrorStateSentError = 4,
  IRPhotoErrorStateRecognitionResultError = 5,
};














SWIFT_CLASS("_TtC10IrLibSwift8RealmInt")
@interface RealmInt : RLMObject
@property (nonatomic) NSInteger integerValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Класс-обертка над String, чтобы иметь возможность работать с примитивами в Realm.
SWIFT_CLASS("_TtC10IrLibSwift11RealmString")
@interface RealmString : RLMObject
@property (nonatomic, copy) NSString * _Nonnull stringValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class RecognitionResultWidth;

SWIFT_CLASS("_TtC10IrLibSwift33RecognitionResultActualAssortment")
@interface RecognitionResultActualAssortment : RLMObject
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic) NSInteger facing;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic) NSInteger priceType;
@property (nonatomic, strong) RecognitionResultWidth * _Nullable width;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RecognitionResultProductGroup;
@class RecognitionResultScene;
@class RecognitionResultSceneGroup;

SWIFT_CLASS("_TtC10IrLibSwift38RecognitionResultAssortmentAchievement")
@interface RecognitionResultAssortmentAchievement : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger facingPlan;
@property (nonatomic) NSInteger facingFact;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic) BOOL isUserBrand;
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, copy) NSString * _Nullable brandName;
@property (nonatomic, copy) NSString * _Nullable brandId;
@property (nonatomic, copy) NSString * _Nullable categoryName;
@property (nonatomic, copy) NSString * _Nullable macrocategoryId;
@property (nonatomic, copy) NSString * _Nullable macrocategoryName;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic) BOOL isKey;
@property (nonatomic) NSInteger facingReal;
@property (nonatomic, strong) RLMArray<RecognitionResultProductGroup *> * _Nonnull productGroup;
@property (nonatomic, strong) RLMArray<RecognitionResultScene *> * _Nonnull scene;
@property (nonatomic, strong) RLMArray<RecognitionResultSceneGroup *> * _Nonnull sceneGroup;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic) BOOL isYellowPrice;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RecognitionResultTotal;
@class RecognitionResultValue;

SWIFT_CLASS("_TtC10IrLibSwift21RecognitionResultLack")
@interface RecognitionResultLack : RLMObject
@property (nonatomic, strong) RecognitionResultTotal * _Nullable total;
@property (nonatomic, strong) RLMArray<RecognitionResultValue *> * _Nonnull values;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift30RecognitionResultOldAssortment")
@interface RecognitionResultOldAssortment : RLMObject
@property (nonatomic, strong) RLMArray<RecognitionResultAssortmentAchievement *> * _Nonnull assortmentAchievement;
@property (nonatomic, strong) RecognitionResultLack * _Nullable lackOfAssortment;
@property (nonatomic) NSInteger performanceAssortment;
@property (nonatomic) NSInteger lackOfAssortmentDelta;
@property (nonatomic) NSInteger performanceAssortmentDelta;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift29RecognitionResultProductGroup")
@interface RecognitionResultProductGroup : RLMObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) NSInteger value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift26RecognitionResultRealogram")
@interface RecognitionResultRealogram : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, copy) NSString * _Nullable tinyName;
@property (nonatomic) NSInteger statusId;
@property (nonatomic) NSInteger x1;
@property (nonatomic) NSInteger y1;
@property (nonatomic) NSInteger x2;
@property (nonatomic) NSInteger y2;
@property (nonatomic) NSInteger x01;
@property (nonatomic) NSInteger y01;
@property (nonatomic) NSInteger x02;
@property (nonatomic) NSInteger y02;
@property (nonatomic) BOOL isUserBrand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultScene")
@interface RecognitionResultScene : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger facingFact;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift27RecognitionResultSceneGroup")
@interface RecognitionResultSceneGroup : RLMObject
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger facingFact;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TaskKpi;

SWIFT_CLASS("_TtC10IrLibSwift21RecognitionResultTask")
@interface RecognitionResultTask : RLMObject
@property (nonatomic, copy) NSString * _Nonnull taskId;
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nullable sourceId;
@property (nonatomic) NSInteger totalScore;
@property (nonatomic) double percentage;
@property (nonatomic) double averagePercentage;
@property (nonatomic, strong) RLMArray<TaskKpi *> * _Nonnull kpis;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultTotal")
@interface RecognitionResultTotal : RLMObject
@property (nonatomic) NSInteger value;
@property (nonatomic) NSInteger previousValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultValue")
@interface RecognitionResultValue : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger plan;
@property (nonatomic) NSInteger fact;
@property (nonatomic, copy) NSString * _Nullable productCategoryName;
@property (nonatomic, copy) NSString * _Nullable miniature;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic) NSInteger reasonId;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) BOOL isUserBrand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultWidth")
@interface RecognitionResultWidth : RLMObject
@property (nonatomic) double cm;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift7Segment")
@interface Segment : RLMObject
@property (nonatomic, copy) NSString * _Nonnull segmentId;
@property (nonatomic) NSInteger segmentPk;
@property (nonatomic, copy) NSString * _Nonnull name;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift5Store")
@interface Store : RLMObject
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nonnull storeIdString;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable retailerName;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic, copy) NSString * _Nullable segmentId;
@property (nonatomic, copy) NSString * _Nullable segmentName;
@property (nonatomic, copy) NSString * _Nullable storeTypeName;
@property (nonatomic) double lat;
@property (nonatomic) double lon;
@property (nonatomic) double distance;
@property (nonatomic, copy) NSString * _Nullable cityName;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP10IrLibSwift18StoresModuleOutput_")
@protocol StoresModuleOutput
- (void)didFinishLoadingCatalogs;
- (void)didTriggerStartShootingForTaskWithId:(NSString * _Nullable)taskId valuesUpdateHandler:(void (^ _Nonnull)(void))valuesUpdateHandler;
- (void)didTriggerOpenOsaReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didTriggerOpenSosReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didTriggerOpenPriceExecutionReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didStartVisitForStoreWithId:(NSInteger)storeId;
- (void)didFinishVisitForStoreWithId:(NSInteger)storeId readyToFinishHandler:(void (^ _Nonnull)(BOOL))readyToFinishHandler;
- (void)didTriggerOpenAssortmentForStoreWithId:(NSInteger)storeId;
- (void)didTriggerOpenSummaryReportForStoreWithId:(NSInteger)storeId;
@end


SWIFT_CLASS("_TtC10IrLibSwift10TaskAnswer")
@interface TaskAnswer : RLMObject
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift14TaskAttachment")
@interface TaskAttachment : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift7TaskKpi")
@interface TaskKpi : RLMObject
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC10IrLibSwift12TaskQuestion")
@interface TaskQuestion : RLMObject
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL isRequired;
@property (nonatomic, strong) RLMArray<TaskAnswer *> * _Nonnull answers;
@property (nonatomic, strong) RLMArray<RealmInt *> * _Nonnull selectedAnswers;
@property (nonatomic, copy) NSString * _Nullable enteredAnswer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









@class VisitWidget;
@class VisitTask;

SWIFT_CLASS("_TtC10IrLibSwift5Visit")
@interface Visit : RLMObject
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, copy) NSString * _Nullable externalUserId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nonnull storeName;
@property (nonatomic, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, copy) NSString * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nonnull timestampFull;
@property (nonatomic, copy) NSString * _Nonnull timestampStart;
@property (nonatomic, copy) NSString * _Nullable timestampEnd;
@property (nonatomic) NSInteger timestampLong;
@property (nonatomic) BOOL isSended;
@property (nonatomic) BOOL isShareShelfReceived;
@property (nonatomic) BOOL isCustomShareShelfReceived;
@property (nonatomic) BOOL isWidgetReceived;
@property (nonatomic) NSInteger notificationsCount;
@property (nonatomic) NSInteger isReportRequested;
@property (nonatomic) BOOL isProductGroupReceived;
@property (nonatomic) BOOL isConfirmedWithReceivedReports;
@property (nonatomic, strong) RLMArray<RecognitionResultTask *> * _Nonnull resultTasks;
@property (nonatomic, strong) RecognitionResultOldAssortment * _Nullable resultOldAssortment;
@property (nonatomic, strong) RLMArray<VisitWidget *> * _Nonnull widgets;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
/// Был ли визит получен с сервера (в рамках запроса предыдущих визитов)
@property (nonatomic) BOOL isDownloaded;
@property (nonatomic, strong) RLMArray<VisitTask *> * _Nonnull tasks;
/// Был ли визит когда-либо завершён
@property (nonatomic) BOOL wasFinished;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable photoIdForGettingOldAssortment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Задача привязанная. Добавляется в базу в момент создания визита и остается неизменной, даже если задача на сервере обновилась
SWIFT_CLASS("_TtC10IrLibSwift9VisitTask")
@interface VisitTask : RLMObject
/// Идентификатор задачи на бэке
@property (nonatomic, copy) NSString * _Nonnull taskId;
@property (nonatomic) NSInteger taskPk;
/// Внутренний идентификатор задачи для привязки к визиту
@property (nonatomic, copy) NSString * _Nonnull internalId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) BOOL isDisabled;
@property (nonatomic) BOOL isRequired;
@property (nonatomic) BOOL shouldUseAllVisitPhotos;
@property (nonatomic) BOOL isPhotoRequired;
@property (nonatomic, strong) RLMArray<RealmString *> * _Nonnull sceneTypeIds;
@property (nonatomic) NSInteger order;
@property (nonatomic, copy) NSString * _Nullable visitImage;
@property (nonatomic, strong) RLMArray<TaskAttachment *> * _Nonnull attachments;
@property (nonatomic, strong) RLMArray<TaskKpi *> * _Nonnull kpis;
@property (nonatomic, strong) RLMArray<TaskQuestion *> * _Nonnull questions;
@property (nonatomic, copy) NSString * _Nonnull matrixType;
@property (nonatomic, copy) NSString * _Nonnull totalScoreCountType;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift11VisitWidget")
@interface VisitWidget : RLMObject
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, strong) RLMArray<VisitWidgetMatrix *> * _Nonnull data;
@property (nonatomic, strong) RLMArray<VisitWidgetTasksData *> * _Nonnull tasksData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class VisitWidgetProduct;

SWIFT_CLASS("_TtC10IrLibSwift26VisitWidgetAssortmentGroup")
@interface VisitWidgetAssortmentGroup : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nullable assortmentGroupName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift16VisitWidgetBrand")
@interface VisitWidgetBrand : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull brandId;
@property (nonatomic, copy) NSString * _Nonnull brandName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift21VisitWidgetBrandOwner")
@interface VisitWidgetBrandOwner : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull brandOwnerId;
@property (nonatomic, copy) NSString * _Nonnull brandOwnerName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift24VisitWidgetMacroCategory")
@interface VisitWidgetMacroCategory : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull macroCategoryId;
@property (nonatomic, copy) NSString * _Nonnull macroCategoryName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
@property (nonatomic) NSInteger value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class VisitWidgetTotal;

SWIFT_CLASS("_TtC10IrLibSwift17VisitWidgetMatrix")
@interface VisitWidgetMatrix : RLMObject
@property (nonatomic, strong) VisitWidgetTotal * _Nullable total;
@property (nonatomic, copy) NSString * _Nonnull matrixType;
@property (nonatomic, copy) NSString * _Nonnull matrixTypeName;
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
@property (nonatomic, strong) RLMArray<VisitWidgetMacroCategory *> * _Nonnull macroCategories;
@property (nonatomic, strong) RLMArray<VisitWidgetBrandOwner *> * _Nonnull brandOwners;
@property (nonatomic, strong) RLMArray<VisitWidgetBrand *> * _Nonnull brands;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift18VisitWidgetProduct")
@interface VisitWidgetProduct : RLMObject
@property (nonatomic) NSInteger plan;
@property (nonatomic) NSInteger facingFact;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) NSInteger other;
@property (nonatomic) NSInteger groupFact;
@property (nonatomic) double price;
@property (nonatomic) NSInteger priceType;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic, copy) NSString * _Nullable tinyName;
@property (nonatomic) NSInteger sceneType;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable productCategoryId;
@property (nonatomic, copy) NSString * _Nullable brandId;
@property (nonatomic, copy) NSString * _Nullable brandOwnerId;
@property (nonatomic) BOOL isUserBrand;
@property (nonatomic, copy) NSString * _Nullable miniature;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger priceStatus;
@property (nonatomic) double minRange;
@property (nonatomic) double maxRange;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic) NSInteger reasonId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRPriceStatus, closed) {
  IRPriceStatusNotDetected = -1,
  IRPriceStatusNotInRange = 0,
  IRPriceStatusInRange = 1,
};

typedef SWIFT_ENUM(NSInteger, IRPriceType, closed) {
  IRPriceTypeEmpty = -1,
  IRPriceTypeCommon = 0,
  IRPriceTypePromo = 1,
};


SWIFT_CLASS("_TtC10IrLibSwift20VisitWidgetTasksData")
@interface VisitWidgetTasksData : RLMObject
@property (nonatomic, copy) NSString * _Nullable taskId;
@property (nonatomic, strong) VisitWidgetTotal * _Nullable total;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, strong) RLMArray<VisitWidgetMatrix *> * _Nonnull matrices;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift16VisitWidgetTotal")
@interface VisitWidgetTotal : RLMObject
@property (nonatomic) NSInteger value;
@property (nonatomic) NSInteger diff;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef IRLIBSWIFT_SWIFT_H
#define IRLIBSWIFT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Realm;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IrLibSwift",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIBarButtonItem;

SWIFT_PROTOCOL("_TtP10IrLibSwift16BarButtonShowing_")
@protocol BarButtonShowing
- (void)addBarButton:(UIBarButtonItem * _Nonnull)button;
@end




SWIFT_CLASS("_TtC10IrLibSwift18IRAuthInfoProvider")
@interface IRAuthInfoProvider : NSObject
@property (nonatomic, copy) NSString * _Nonnull userToken;
@property (nonatomic, copy) NSString * _Nonnull basePath;
@property (nonatomic, copy) NSString * _Nonnull domain;
@property (nonatomic) BOOL isMultiportal;
- (nonnull instancetype)initWithUserToken:(NSString * _Nonnull)userToken basePath:(NSString * _Nonnull)basePath domain:(NSString * _Nonnull)domain isMultiportal:(BOOL)isMultiportal OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RLMRealmConfiguration;
@class NSNumber;

SWIFT_PROTOCOL("_TtP10IrLibSwift26IRDataBaseSettingsProvider_")
@protocol IRDataBaseSettingsProvider
@property (nonatomic, readonly, strong) RLMRealmConfiguration * _Nonnull realmConfig;
@property (nonatomic, readonly, strong) NSNumber * _Nullable previousDbVersion;
@end

@class NSError;
@class Photo;
@class IRDataManagerSettings;
@class Visit;
@class VisitWidgetMatrix;
@class VisitWidgetMacroCategory;
@class VisitWidgetTasksData;

SWIFT_PROTOCOL("_TtP10IrLibSwift21IRDataManagerProtocol_")
@protocol IRDataManagerProtocol
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)clearStoresLoadDate;
- (BOOL)createVisitWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId error:(NSError * _Nullable * _Nullable)error;
- (void)sendCurrentVisit;
- (void)fetchRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)sendPhotoWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Photo *> * _Nonnull)photosReadyToSendWithVisitId:(NSString * _Nullable)visitId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)recognitionResultRecivedCompletelyForPhotoWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Photo *> * _Nonnull)photosWithNoRecognitionResult SWIFT_WARN_UNUSED_RESULT;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)updateCurrentUserWithName:(NSString * _Nonnull)name externalId:(NSString * _Nonnull)externalId;
- (void)updateSettingsFrom:(IRDataManagerSettings * _Nonnull)settings;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Visit *> * _Nonnull)visitsWithNoWidgets SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)defaultMatrixFromVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMacroCategory *> * _Nullable)widgetMacroCategoriesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nullable)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)widgetMatrixForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMatrix *> * _Nullable)widgetMatricesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetTasksData *> * _Nullable)widgetTasksForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType SWIFT_WARN_UNUSED_RESULT;
- (void)updateProductForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId macroCategoryId:(NSString * _Nonnull)macroCategoryId productId:(NSString * _Nonnull)productId reasonId:(NSInteger)reasonId comment:(NSString * _Nullable)comment;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitsWithLimit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)downloadPhotosForPreviousVisitsWithVisitId:(NSString * _Nullable)visitId limit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (void)addSendSceneBlockToSequenceWithSceneId:(NSString * _Nonnull)sceneId block:(void (^ _Nonnull)(void))block;
- (void)restartSendPhotoSequenceWithResetAttemptIntervals:(BOOL)resetAttemptIntervals completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)deletePhotoWithId:(NSString * _Nonnull)id;
- (void)cancelRequests;
@end


SWIFT_CLASS("_TtC10IrLibSwift13IRDataManager")
@interface IRDataManager : NSObject <IRDataManagerProtocol>
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
+ (void)updateAppInfoWithIsApp:(BOOL)isApp;
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)clearStoresLoadDate;
- (BOOL)createVisitWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId error:(NSError * _Nullable * _Nullable)error;
- (void)sendCurrentVisit;
- (void)fetchRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)restartSendPhotoSequenceWithResetAttemptIntervals:(BOOL)resetAttemptIntervals completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)sendPhotoWithPhotoId:(NSString * _Nonnull)photoId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Взаимодействие с новым классом Photo
- (NSArray<Photo *> * _Nonnull)photosReadyToSendWithVisitId:(NSString * _Nullable)visitId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)recognitionResultRecivedCompletelyForPhotoWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Photo *> * _Nonnull)photosWithNoRecognitionResult SWIFT_WARN_UNUSED_RESULT;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
/// Обновление выбранной торговой точки. Используется в случае работы с либой / через диплинки.
/// \param storeId идентификатор торговой точки
///
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)updateCurrentUserWithName:(NSString * _Nonnull)name externalId:(NSString * _Nonnull)externalId;
- (void)updateSettingsFrom:(IRDataManagerSettings * _Nonnull)settings;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<Visit *> * _Nonnull)visitsWithNoWidgets SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)defaultMatrixFromVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMacroCategory *> * _Nullable)widgetMacroCategoriesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nullable)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetMatrix * _Nullable)widgetMatrixForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetMatrix *> * _Nullable)widgetMatricesForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VisitWidgetTasksData *> * _Nullable)widgetTasksForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType SWIFT_WARN_UNUSED_RESULT;
- (void)updateProductForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId macroCategoryId:(NSString * _Nonnull)macroCategoryId productId:(NSString * _Nonnull)productId reasonId:(NSInteger)reasonId comment:(NSString * _Nullable)comment;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSInteger)cachedTasksCount SWIFT_WARN_UNUSED_RESULT;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitsWithLimit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchPreviousVisitWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)downloadPhotosForPreviousVisitsWithVisitId:(NSString * _Nullable)visitId limit:(NSInteger)limit completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (void)addSendSceneBlockToSequenceWithSceneId:(NSString * _Nonnull)sceneId block:(void (^ _Nonnull)(void))block;
- (void)deletePhotoWithId:(NSString * _Nonnull)id;
- (void)cancelRequests;
- (NSInteger)saveStoreWithExternalId:(NSString * _Nonnull)externalId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class IRSharedSettings;

/// Класс для настройки IRDataManager.
SWIFT_CLASS("_TtC10IrLibSwift21IRDataManagerSettings")
@interface IRDataManagerSettings : NSObject
- (nonnull instancetype)initWithAuthInfoProvider:(IRAuthInfoProvider * _Nonnull)authInfoProvider dbSettingsProvider:(id <IRDataBaseSettingsProvider> _Nonnull)dbSettingsProvider sharedSettings:(IRSharedSettings * _Nonnull)sharedSettings installId:(NSString * _Nonnull)installId notificationPrefix:(NSString * _Nullable)notificationPrefix OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum IRLocationErrorBlockType : NSInteger;

/// Настройки запретов на съёмку в зависимости от геолокации
SWIFT_CLASS("_TtC10IrLibSwift32IRGeolocationErrorSharedSettings")
@interface IRGeolocationErrorSharedSettings : NSObject
@property (nonatomic) enum IRLocationErrorBlockType type;
@property (nonatomic) NSInteger threshold;
- (nonnull instancetype)initWithType:(enum IRLocationErrorBlockType)type threshold:(NSInteger)threshold OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, IRLocationErrorBlockType, closed) {
  IRLocationErrorBlockTypeNone = 0,
  IRLocationErrorBlockTypeFull = 1,
  IRLocationErrorBlockTypePartial = 2,
};

typedef SWIFT_ENUM(NSInteger, IRNetworkError, closed) {
  IRNetworkErrorNoConnection = 503,
  IRNetworkErrorAuthError = 403,
  IRNetworkErrorProcessing = 202,
  IRNetworkErrorServerError = 500,
  IRNetworkErrorDecodeError = 901,
  IRNetworkErrorEncodeError = 902,
  IRNetworkErrorResponseDecodeError = 903,
  IRNetworkErrorUnknown = -1,
};

@protocol StoresModuleOutput;
@class UIViewController;

SWIFT_CLASS("_TtC10IrLibSwift19IRNewScreensBuilder")
@interface IRNewScreensBuilder : NSObject
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nonnull)storesScreenWithOutput:(id <StoresModuleOutput> _Nonnull)output SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift14IRNotification")
@interface IRNotification : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull authErrorNotification;)
+ (NSNotificationName _Nonnull)authErrorNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRPhotoApproveMode, closed) {
  IRPhotoApproveModeManual = 0,
  IRPhotoApproveModeAutomatic = 1,
};

@class IRStoresSharedSettings;

/// Группа классов ответственная за общие настройки библиотеки, получаемые с сервера в запросе getSettings.
/// Временное решение для передачи необходимых настроек из старой либы в новую. Позже запрос на getSettings будет вынесен в эту либу.
SWIFT_CLASS("_TtC10IrLibSwift16IRSharedSettings")
@interface IRSharedSettings : NSObject
@property (nonatomic, readonly, strong) IRStoresSharedSettings * _Nullable storesSettings;
@property (nonatomic, readonly, strong) IRGeolocationErrorSharedSettings * _Nonnull locationError;
@property (nonatomic, readonly) enum IRPhotoApproveMode photoApproveMode;
@property (nonatomic, readonly) BOOL shouldSyncManually;
- (nonnull instancetype)initWithStoresSettings:(IRStoresSharedSettings * _Nonnull)storesSettings locationError:(IRGeolocationErrorSharedSettings * _Nonnull)locationError photoApproveMode:(enum IRPhotoApproveMode)photoApproveMode shouldSyncManually:(BOOL)shouldSyncManually OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift27IRStoredClassesInfoProvider")
@interface IRStoredClassesInfoProvider : NSObject
+ (NSArray * _Nonnull)storedClasses SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class IRStoredStateSettingsVisit;
@class IRStoredStateSettingsStore;

/// Хранимые настройки текущего состояния - идентификаторы текущего визита, торговой точки и тому подобное.
/// Ojbc-библиотека использует этот класс для получения и обновления актуальных данных.
SWIFT_CLASS("_TtC10IrLibSwift21IRStoredStateSettings")
@interface IRStoredStateSettings : NSObject
- (nonnull instancetype)initWithSettings:(IRDataManagerSettings * _Nonnull)settings OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) IRStoredStateSettingsVisit * _Nullable currentVisit;
@property (nonatomic, readonly, strong) IRStoredStateSettingsStore * _Nullable currentStore;
- (void)clearCurrentVisit;
- (void)updateCurrentStoreId:(NSInteger)storeId;
- (void)updateCurrentExternalStoreId:(NSString * _Nonnull)externalStoreId;
- (void)updateCurrentUserWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name externalId:(NSString * _Nullable)externalId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsStore")
@interface IRStoredStateSettingsStore : NSObject
@property (nonatomic, readonly) NSInteger storeId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsVisit")
@interface IRStoredStateSettingsVisit : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull visitId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalVisitId;
@property (nonatomic, readonly, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nullable externalUserId;
@property (nonatomic, readonly, copy) NSString * _Nonnull startTimestamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift22IRStoresSharedSettings")
@interface IRStoresSharedSettings : NSObject
@property (nonatomic, strong) NSNumber * _Nullable forceUpdateInterval;
- (nonnull instancetype)initWithForceUpdateInterval:(NSNumber * _Nullable)forceUpdateInterval OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class RecognitionResultRealogram;
@class RecognitionResultActualAssortment;

SWIFT_CLASS("_TtC10IrLibSwift5Photo")
@interface Photo : RLMObject
@property (nonatomic, copy) NSString * _Nonnull photoId;
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nullable externalVisitId;
@property (nonatomic, copy) NSString * _Nonnull sceneId;
@property (nonatomic) NSInteger sceneTypeId;
@property (nonatomic, copy) NSString * _Nonnull sceneTypeName;
@property (nonatomic, copy) NSString * _Nullable taskId;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSDate * _Nullable createdTime;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
/// Скачано ли это фото с портала
@property (nonatomic) BOOL isDownloaded;
/// Скачано ли изображение для этого фото
@property (nonatomic) BOOL isImageDownloaded;
@property (nonatomic) NSInteger state;
@property (nonatomic) NSInteger sceneNumber;
@property (nonatomic) NSInteger photoNumber;
@property (nonatomic) NSInteger innerNumber;
@property (nonatomic) NSInteger maxNumber;
/// Результат анализа
@property (nonatomic) NSInteger blur;
@property (nonatomic) BOOL isQualityError;
@property (nonatomic) BOOL isGeolocationError;
@property (nonatomic) BOOL isTiltAngleError;
@property (nonatomic) BOOL isApproved;
@property (nonatomic) BOOL isSelected;
@property (nonatomic) BOOL isSceneClosed;
/// Ошибки
@property (nonatomic) NSInteger errorState;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
/// Отправка на сервер и получение результата
@property (nonatomic) NSInteger sendPhotoAttemptsCounter;
@property (nonatomic) NSInteger timeNextAttemptToSendPhoto;
/// Время следующей попытки отправить фото
@property (nonatomic) NSInteger recognitionResultAttemptsCounter;
@property (nonatomic) NSInteger timeNextAttemptToRecognitionResult;
/// Время следующей попытки отправить запрос отчета
/// Результаты распознования
@property (nonatomic, strong) RLMArray<RecognitionResultRealogram *> * _Nonnull realogram;
@property (nonatomic, strong) RLMArray<RecognitionResultActualAssortment *> * _Nonnull actualAssortment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Новые типы можно добавлять только в конец, так как порядок имеет значение. Перемешивать после публикации новой версии тоже не стоит
/// В objC вызов вида IRPhotoStateВeleted
typedef SWIFT_ENUM(NSInteger, IRPhotoState, closed) {
  IRPhotoStateDeleted = 1,
  IRPhotoStateNotReadyToSend = 2,
  IRPhotoStateReadyToSend = 3,
  IRPhotoStateNotStitched = 4,
  IRPhotoStateNotAnalysed = 5,
  IRPhotoStateNotSaved = 6,
  IRPhotoStateSent = 7,
  IRPhotoStateFinished = 8,
};

/// Статусы ошибок, пока они нужны так как старая логика сильно завязана, в дальнейшем можно будет перенести ошибки в IRPhotoState как статус отправки
typedef SWIFT_ENUM(NSInteger, IRPhotoErrorState, closed) {
  IRPhotoErrorStateNoError = 1,
  IRPhotoErrorStateAnalyseError = 2,
  IRPhotoErrorStateStitcherError = 3,
  IRPhotoErrorStateSentError = 4,
  IRPhotoErrorStateRecognitionResultError = 5,
};














SWIFT_CLASS("_TtC10IrLibSwift8RealmInt")
@interface RealmInt : RLMObject
@property (nonatomic) NSInteger integerValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Класс-обертка над String, чтобы иметь возможность работать с примитивами в Realm.
SWIFT_CLASS("_TtC10IrLibSwift11RealmString")
@interface RealmString : RLMObject
@property (nonatomic, copy) NSString * _Nonnull stringValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class RecognitionResultWidth;

SWIFT_CLASS("_TtC10IrLibSwift33RecognitionResultActualAssortment")
@interface RecognitionResultActualAssortment : RLMObject
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic) NSInteger facing;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic) NSInteger priceType;
@property (nonatomic, strong) RecognitionResultWidth * _Nullable width;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RecognitionResultProductGroup;
@class RecognitionResultScene;
@class RecognitionResultSceneGroup;

SWIFT_CLASS("_TtC10IrLibSwift38RecognitionResultAssortmentAchievement")
@interface RecognitionResultAssortmentAchievement : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger facingPlan;
@property (nonatomic) NSInteger facingFact;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic) BOOL isUserBrand;
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, copy) NSString * _Nullable brandName;
@property (nonatomic, copy) NSString * _Nullable brandId;
@property (nonatomic, copy) NSString * _Nullable categoryName;
@property (nonatomic, copy) NSString * _Nullable macrocategoryId;
@property (nonatomic, copy) NSString * _Nullable macrocategoryName;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic) BOOL isKey;
@property (nonatomic) NSInteger facingReal;
@property (nonatomic, strong) RLMArray<RecognitionResultProductGroup *> * _Nonnull productGroup;
@property (nonatomic, strong) RLMArray<RecognitionResultScene *> * _Nonnull scene;
@property (nonatomic, strong) RLMArray<RecognitionResultSceneGroup *> * _Nonnull sceneGroup;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic) BOOL isYellowPrice;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RecognitionResultTotal;
@class RecognitionResultValue;

SWIFT_CLASS("_TtC10IrLibSwift21RecognitionResultLack")
@interface RecognitionResultLack : RLMObject
@property (nonatomic, strong) RecognitionResultTotal * _Nullable total;
@property (nonatomic, strong) RLMArray<RecognitionResultValue *> * _Nonnull values;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift30RecognitionResultOldAssortment")
@interface RecognitionResultOldAssortment : RLMObject
@property (nonatomic, strong) RLMArray<RecognitionResultAssortmentAchievement *> * _Nonnull assortmentAchievement;
@property (nonatomic, strong) RecognitionResultLack * _Nullable lackOfAssortment;
@property (nonatomic) NSInteger performanceAssortment;
@property (nonatomic) NSInteger lackOfAssortmentDelta;
@property (nonatomic) NSInteger performanceAssortmentDelta;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift29RecognitionResultProductGroup")
@interface RecognitionResultProductGroup : RLMObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) NSInteger value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift26RecognitionResultRealogram")
@interface RecognitionResultRealogram : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, copy) NSString * _Nullable tinyName;
@property (nonatomic) NSInteger statusId;
@property (nonatomic) NSInteger x1;
@property (nonatomic) NSInteger y1;
@property (nonatomic) NSInteger x2;
@property (nonatomic) NSInteger y2;
@property (nonatomic) NSInteger x01;
@property (nonatomic) NSInteger y01;
@property (nonatomic) NSInteger x02;
@property (nonatomic) NSInteger y02;
@property (nonatomic) BOOL isUserBrand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultScene")
@interface RecognitionResultScene : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger facingFact;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift27RecognitionResultSceneGroup")
@interface RecognitionResultSceneGroup : RLMObject
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger facingFact;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TaskKpi;

SWIFT_CLASS("_TtC10IrLibSwift21RecognitionResultTask")
@interface RecognitionResultTask : RLMObject
@property (nonatomic, copy) NSString * _Nonnull taskId;
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nullable sourceId;
@property (nonatomic) NSInteger totalScore;
@property (nonatomic) double percentage;
@property (nonatomic) double averagePercentage;
@property (nonatomic, strong) RLMArray<TaskKpi *> * _Nonnull kpis;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultTotal")
@interface RecognitionResultTotal : RLMObject
@property (nonatomic) NSInteger value;
@property (nonatomic) NSInteger previousValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultValue")
@interface RecognitionResultValue : RLMObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger plan;
@property (nonatomic) NSInteger fact;
@property (nonatomic, copy) NSString * _Nullable productCategoryName;
@property (nonatomic, copy) NSString * _Nullable miniature;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic) NSInteger reasonId;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) BOOL isUserBrand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultWidth")
@interface RecognitionResultWidth : RLMObject
@property (nonatomic) double cm;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift7Segment")
@interface Segment : RLMObject
@property (nonatomic, copy) NSString * _Nonnull segmentId;
@property (nonatomic) NSInteger segmentPk;
@property (nonatomic, copy) NSString * _Nonnull name;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift5Store")
@interface Store : RLMObject
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nonnull storeIdString;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable retailerName;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic, copy) NSString * _Nullable segmentId;
@property (nonatomic, copy) NSString * _Nullable segmentName;
@property (nonatomic, copy) NSString * _Nullable storeTypeName;
@property (nonatomic) double lat;
@property (nonatomic) double lon;
@property (nonatomic) double distance;
@property (nonatomic, copy) NSString * _Nullable cityName;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP10IrLibSwift18StoresModuleOutput_")
@protocol StoresModuleOutput
- (void)didFinishLoadingCatalogs;
- (void)didTriggerStartShootingForTaskWithId:(NSString * _Nullable)taskId valuesUpdateHandler:(void (^ _Nonnull)(void))valuesUpdateHandler;
- (void)didTriggerOpenOsaReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didTriggerOpenSosReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didTriggerOpenPriceExecutionReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didStartVisitForStoreWithId:(NSInteger)storeId;
- (void)didFinishVisitForStoreWithId:(NSInteger)storeId readyToFinishHandler:(void (^ _Nonnull)(BOOL))readyToFinishHandler;
- (void)didTriggerOpenAssortmentForStoreWithId:(NSInteger)storeId;
- (void)didTriggerOpenSummaryReportForStoreWithId:(NSInteger)storeId;
@end


SWIFT_CLASS("_TtC10IrLibSwift10TaskAnswer")
@interface TaskAnswer : RLMObject
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift14TaskAttachment")
@interface TaskAttachment : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift7TaskKpi")
@interface TaskKpi : RLMObject
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC10IrLibSwift12TaskQuestion")
@interface TaskQuestion : RLMObject
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL isRequired;
@property (nonatomic, strong) RLMArray<TaskAnswer *> * _Nonnull answers;
@property (nonatomic, strong) RLMArray<RealmInt *> * _Nonnull selectedAnswers;
@property (nonatomic, copy) NSString * _Nullable enteredAnswer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









@class VisitWidget;
@class VisitTask;

SWIFT_CLASS("_TtC10IrLibSwift5Visit")
@interface Visit : RLMObject
@property (nonatomic, copy) NSString * _Nonnull visitId;
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, copy) NSString * _Nullable externalUserId;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic) NSInteger storeId;
@property (nonatomic, copy) NSString * _Nonnull storeName;
@property (nonatomic, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, copy) NSString * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nonnull timestampFull;
@property (nonatomic, copy) NSString * _Nonnull timestampStart;
@property (nonatomic, copy) NSString * _Nullable timestampEnd;
@property (nonatomic) NSInteger timestampLong;
@property (nonatomic) BOOL isSended;
@property (nonatomic) BOOL isShareShelfReceived;
@property (nonatomic) BOOL isCustomShareShelfReceived;
@property (nonatomic) BOOL isWidgetReceived;
@property (nonatomic) NSInteger notificationsCount;
@property (nonatomic) NSInteger isReportRequested;
@property (nonatomic) BOOL isProductGroupReceived;
@property (nonatomic) BOOL isConfirmedWithReceivedReports;
@property (nonatomic, strong) RLMArray<RecognitionResultTask *> * _Nonnull resultTasks;
@property (nonatomic, strong) RecognitionResultOldAssortment * _Nullable resultOldAssortment;
@property (nonatomic, strong) RLMArray<VisitWidget *> * _Nonnull widgets;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
/// Был ли визит получен с сервера (в рамках запроса предыдущих визитов)
@property (nonatomic) BOOL isDownloaded;
@property (nonatomic, strong) RLMArray<VisitTask *> * _Nonnull tasks;
/// Был ли визит когда-либо завершён
@property (nonatomic) BOOL wasFinished;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable photoIdForGettingOldAssortment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Задача привязанная. Добавляется в базу в момент создания визита и остается неизменной, даже если задача на сервере обновилась
SWIFT_CLASS("_TtC10IrLibSwift9VisitTask")
@interface VisitTask : RLMObject
/// Идентификатор задачи на бэке
@property (nonatomic, copy) NSString * _Nonnull taskId;
@property (nonatomic) NSInteger taskPk;
/// Внутренний идентификатор задачи для привязки к визиту
@property (nonatomic, copy) NSString * _Nonnull internalId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) BOOL isDisabled;
@property (nonatomic) BOOL isRequired;
@property (nonatomic) BOOL shouldUseAllVisitPhotos;
@property (nonatomic) BOOL isPhotoRequired;
@property (nonatomic, strong) RLMArray<RealmString *> * _Nonnull sceneTypeIds;
@property (nonatomic) NSInteger order;
@property (nonatomic, copy) NSString * _Nullable visitImage;
@property (nonatomic, strong) RLMArray<TaskAttachment *> * _Nonnull attachments;
@property (nonatomic, strong) RLMArray<TaskKpi *> * _Nonnull kpis;
@property (nonatomic, strong) RLMArray<TaskQuestion *> * _Nonnull questions;
@property (nonatomic, copy) NSString * _Nonnull matrixType;
@property (nonatomic, copy) NSString * _Nonnull totalScoreCountType;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift11VisitWidget")
@interface VisitWidget : RLMObject
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, strong) RLMArray<VisitWidgetMatrix *> * _Nonnull data;
@property (nonatomic, strong) RLMArray<VisitWidgetTasksData *> * _Nonnull tasksData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class VisitWidgetProduct;

SWIFT_CLASS("_TtC10IrLibSwift26VisitWidgetAssortmentGroup")
@interface VisitWidgetAssortmentGroup : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nullable assortmentGroupName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift16VisitWidgetBrand")
@interface VisitWidgetBrand : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull brandId;
@property (nonatomic, copy) NSString * _Nonnull brandName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift21VisitWidgetBrandOwner")
@interface VisitWidgetBrandOwner : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull brandOwnerId;
@property (nonatomic, copy) NSString * _Nonnull brandOwnerName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift24VisitWidgetMacroCategory")
@interface VisitWidgetMacroCategory : RLMObject
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, copy) NSString * _Nonnull macroCategoryId;
@property (nonatomic, copy) NSString * _Nonnull macroCategoryName;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
@property (nonatomic) NSInteger value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class VisitWidgetTotal;

SWIFT_CLASS("_TtC10IrLibSwift17VisitWidgetMatrix")
@interface VisitWidgetMatrix : RLMObject
@property (nonatomic, strong) VisitWidgetTotal * _Nullable total;
@property (nonatomic, copy) NSString * _Nonnull matrixType;
@property (nonatomic, copy) NSString * _Nonnull matrixTypeName;
@property (nonatomic) NSInteger planBySku;
@property (nonatomic) NSInteger osaBySku;
@property (nonatomic) double osaBySkuPercentage;
@property (nonatomic) NSInteger planByShelf;
@property (nonatomic) NSInteger osaByShelf;
@property (nonatomic) double osaByShelfPercentage;
@property (nonatomic) NSInteger planByFacing;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) double osaByFacingPercentage;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, strong) RLMArray<VisitWidgetAssortmentGroup *> * _Nonnull assortmentGroups;
@property (nonatomic, strong) RLMArray<VisitWidgetMacroCategory *> * _Nonnull macroCategories;
@property (nonatomic, strong) RLMArray<VisitWidgetBrandOwner *> * _Nonnull brandOwners;
@property (nonatomic, strong) RLMArray<VisitWidgetBrand *> * _Nonnull brands;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift18VisitWidgetProduct")
@interface VisitWidgetProduct : RLMObject
@property (nonatomic) NSInteger plan;
@property (nonatomic) NSInteger facingFact;
@property (nonatomic) NSInteger osaByFacing;
@property (nonatomic) NSInteger other;
@property (nonatomic) NSInteger groupFact;
@property (nonatomic) double price;
@property (nonatomic) NSInteger priceType;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic, copy) NSString * _Nullable tinyName;
@property (nonatomic) NSInteger sceneType;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable productCategoryId;
@property (nonatomic, copy) NSString * _Nullable brandId;
@property (nonatomic, copy) NSString * _Nullable brandOwnerId;
@property (nonatomic) BOOL isUserBrand;
@property (nonatomic, copy) NSString * _Nullable miniature;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger priceStatus;
@property (nonatomic) double minRange;
@property (nonatomic) double maxRange;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic) NSInteger reasonId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRPriceStatus, closed) {
  IRPriceStatusNotDetected = -1,
  IRPriceStatusNotInRange = 0,
  IRPriceStatusInRange = 1,
};

typedef SWIFT_ENUM(NSInteger, IRPriceType, closed) {
  IRPriceTypeEmpty = -1,
  IRPriceTypeCommon = 0,
  IRPriceTypePromo = 1,
};


SWIFT_CLASS("_TtC10IrLibSwift20VisitWidgetTasksData")
@interface VisitWidgetTasksData : RLMObject
@property (nonatomic, copy) NSString * _Nullable taskId;
@property (nonatomic, strong) VisitWidgetTotal * _Nullable total;
@property (nonatomic, strong) RLMArray<VisitWidgetProduct *> * _Nonnull products;
@property (nonatomic, strong) RLMArray<VisitWidgetMatrix *> * _Nonnull matrices;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift16VisitWidgetTotal")
@interface VisitWidgetTotal : RLMObject
@property (nonatomic) NSInteger value;
@property (nonatomic) NSInteger diff;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
