#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef IRLIBSWIFT_SWIFT_H
#define IRLIBSWIFT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import Realm;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IrLibSwift",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class AiletColorsBackground;
@class AiletColorsInteractive;
@class AiletColorsText;
@class AiletColorsIcon;
@class AiletColorsInput;
@class AiletColorsSupport;
@class AiletColorsBorder;
@class AiletColorsAccent;
@class AiletColorsGradient;

/// Структура цветов, используемых в проекте - для использования в objective-c.
SWIFT_CLASS("_TtC10IrLibSwift11AiletColors")
@interface AiletColors : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsBackground * _Nonnull background;)
+ (AiletColorsBackground * _Nonnull)background SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsInteractive * _Nonnull interactive;)
+ (AiletColorsInteractive * _Nonnull)interactive SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsText * _Nonnull text;)
+ (AiletColorsText * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsIcon * _Nonnull icon;)
+ (AiletColorsIcon * _Nonnull)icon SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsInput * _Nonnull input;)
+ (AiletColorsInput * _Nonnull)input SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsSupport * _Nonnull support;)
+ (AiletColorsSupport * _Nonnull)support SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsBorder * _Nonnull border;)
+ (AiletColorsBorder * _Nonnull)border SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsAccent * _Nonnull accent;)
+ (AiletColorsAccent * _Nonnull)accent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletColorsGradient * _Nonnull gradient;)
+ (AiletColorsGradient * _Nonnull)gradient SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end

@class UIColor;

SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors17AiletColorsBorder")
@interface AiletColorsBorder : NSObject
/// $border-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end

@class AiletGradientColor;

SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors19AiletColorsGradient")
@interface AiletColorsGradient : NSObject
/// $gradient-01, blue
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient01;
/// $gradient-02, red
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient02;
/// $gradient-03, violet
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient03;
/// $gradient-04, gray
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient04;
/// $gradient-06, green
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient06;
/// $gradient-07, mavi
@property (nonatomic, readonly, strong) AiletGradientColor * _Nonnull gradient07;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors17AiletColorsAccent")
@interface AiletColorsAccent : NSObject
/// $accent-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent01;
/// $accent-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent02;
/// $accent-03
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent03;
/// $accent-04
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent04;
/// $accent-05
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent05;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors22AiletColorsInteractive")
@interface AiletColorsInteractive : NSObject
/// $interactive-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
/// $interactive-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors21AiletColorsBackground")
@interface AiletColorsBackground : NSObject
/// $ui-bg, wihte
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
/// $ui-01, gray10
@property (nonatomic, readonly, strong) UIColor * _Nonnull background01;
/// $ui-02, gray20
@property (nonatomic, readonly, strong) UIColor * _Nonnull background02;
/// $ui-03, gray30
@property (nonatomic, readonly, strong) UIColor * _Nonnull background03;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors18AiletColorsSupport")
@interface AiletColorsSupport : NSObject
/// $support-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull error;
/// $support-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull success;
/// $support-03
@property (nonatomic, readonly, strong) UIColor * _Nonnull warning;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors16AiletColorsInput")
@interface AiletColorsInput : NSObject
/// $field-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
/// $field-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors15AiletColorsIcon")
@interface AiletColorsIcon : NSObject
/// $icon-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
/// $icon-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondary;
/// $icon-04
@property (nonatomic, readonly, strong) UIColor * _Nonnull onInteractiveColors;
/// $icon-05
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent01;
/// $icon-06
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent02;
/// $icon-07
@property (nonatomic, readonly, strong) UIColor * _Nonnull accent03;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletColors (SWIFT_EXTENSION(IrLibSwift))
@end


SWIFT_CLASS("_TtCC10IrLibSwift11AiletColors15AiletColorsText")
@interface AiletColorsText : NSObject
/// $text-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull primary;
/// $text-02
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondary;
/// $text-03
@property (nonatomic, readonly, strong) UIColor * _Nonnull placeholder;
/// $text-04
@property (nonatomic, readonly, strong) UIColor * _Nonnull interactive;
/// $text-error
@property (nonatomic, readonly, strong) UIColor * _Nonnull error;
/// $text-success
@property (nonatomic, readonly, strong) UIColor * _Nonnull success;
/// $link-01
@property (nonatomic, readonly, strong) UIColor * _Nonnull links;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AiletFontsCaption;
@class AiletFontsSubheadline;
@class AiletFontsHeadline;

SWIFT_CLASS("_TtC10IrLibSwift10AiletFonts")
@interface AiletFonts : NSObject
/// 12pt
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletFontsCaption * _Nonnull caption;)
+ (AiletFontsCaption * _Nonnull)caption SWIFT_WARN_UNUSED_RESULT;
/// 15pt
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletFontsSubheadline * _Nonnull subheadline;)
+ (AiletFontsSubheadline * _Nonnull)subheadline SWIFT_WARN_UNUSED_RESULT;
/// 16pt
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletFontsSubheadline * _Nonnull callout;)
+ (AiletFontsSubheadline * _Nonnull)callout SWIFT_WARN_UNUSED_RESULT;
/// 17pt
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AiletFontsHeadline * _Nonnull headline;)
+ (AiletFontsHeadline * _Nonnull)headline SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AiletFonts (SWIFT_EXTENSION(IrLibSwift))
@end

@class UIFont;

/// 12pt
SWIFT_CLASS("_TtCC10IrLibSwift10AiletFonts17AiletFontsCaption")
@interface AiletFontsCaption : NSObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull normal;
@property (nonatomic, readonly, strong) UIFont * _Nonnull semibold;
@property (nonatomic, readonly, strong) UIFont * _Nonnull italic;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 15pt
SWIFT_CLASS("_TtCC10IrLibSwift10AiletFonts21AiletFontsSubheadline")
@interface AiletFontsSubheadline : NSObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull normal;
@property (nonatomic, readonly, strong) UIFont * _Nonnull semibold;
@property (nonatomic, readonly, strong) UIFont * _Nonnull italic;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 16pt
SWIFT_CLASS("_TtCC10IrLibSwift10AiletFonts17AiletFontsCallout")
@interface AiletFontsCallout : NSObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull normal;
@property (nonatomic, readonly, strong) UIFont * _Nonnull semibold;
@property (nonatomic, readonly, strong) UIFont * _Nonnull italic;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 17pt
SWIFT_CLASS("_TtCC10IrLibSwift10AiletFonts18AiletFontsHeadline")
@interface AiletFontsHeadline : NSObject
@property (nonatomic, readonly, strong) UIFont * _Nonnull normal;
@property (nonatomic, readonly, strong) UIFont * _Nonnull semibold;
@property (nonatomic, readonly, strong) UIFont * _Nonnull italic;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class IRGradientDirection;

SWIFT_CLASS("_TtC10IrLibSwift18AiletGradientColor")
@interface AiletGradientColor : NSObject
@property (nonatomic, readonly, copy) NSArray<UIColor *> * _Nonnull colors;
@property (nonatomic, readonly, strong) IRGradientDirection * _Nonnull direction;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, AiletNetworkError, open) {
  AiletNetworkErrorNoConnection = 503,
  AiletNetworkErrorNotFound = 404,
  AiletNetworkErrorConflict = 409,
  AiletNetworkErrorAuthError = 403,
  AiletNetworkErrorProcessing = 202,
  AiletNetworkErrorServerError = 500,
  AiletNetworkErrorDecodeError = 901,
  AiletNetworkErrorEncodeError = 902,
  AiletNetworkErrorIncorrectUrl = -998,
  AiletNetworkErrorEmptyResponseError = 903,
  AiletNetworkErrorRetryError = 904,
  AiletNetworkErrorNoContent = 204,
  AiletNetworkErrorUnknown = -1,
  AiletNetworkErrorCancelled = -999,
};
static NSString * _Nonnull const AiletNetworkErrorDomain = @"IrLibSwift.AiletNetworkError";

@class NSString;

SWIFT_CLASS("_TtC10IrLibSwift26AiletUnsentDataCheckResult")
@interface AiletUnsentDataCheckResult : NSObject
@property (nonatomic, readonly) BOOL hasUnsentData;
@property (nonatomic, readonly, copy) NSString * _Nullable errorLog;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIBarButtonItem;

SWIFT_PROTOCOL("_TtP10IrLibSwift16BarButtonShowing_")
@protocol BarButtonShowing
- (void)addBarButton:(UIBarButtonItem * _Nonnull)button onTap:(void (^ _Nullable)(void))onTap;
@end






SWIFT_PROTOCOL("_TtP10IrLibSwift18CameraModuleOutput_")
@protocol CameraModuleOutput
- (void)didCompleteCapture;
@end

@class NSCoder;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC10IrLibSwift19CustomImageCheckbox")
@interface CustomImageCheckbox : UIButton
@property (nonatomic, copy) void (^ _Nullable selectedHandler)(BOOL);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, getter=isSelected) BOOL selected;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end


@interface CustomImageCheckbox (SWIFT_EXTENSION(IrLibSwift))
- (void)setIsSelected:(BOOL)isSelected;
@end


SWIFT_PROTOCOL("_TtP10IrLibSwift21WidgetsViewController_")
@protocol WidgetsViewController
- (void)load;
@end


SWIFT_CLASS("_TtC10IrLibSwift28DefaultWidgetsViewController")
@interface DefaultWidgetsViewController : NSObject <WidgetsViewController>
- (void)load;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift12DeletedPhoto")
@interface DeletedPhoto : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRDeletedPhotoState, open) {
  IRDeletedPhotoStateReadyToSend = 1,
  IRDeletedPhotoStateSent = 2,
  IRDeletedPhotoStateFinished = 3,
};



SWIFT_CLASS("_TtC10IrLibSwift31DiagramReportCollectionViewCell")
@interface DiagramReportCollectionViewCell : UICollectionViewCell
@property (nonatomic, copy) void (^ _Nullable titleTapHandler)(void);
@property (nonatomic, copy) void (^ _Nullable reportTapHandler)(void);
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull nibName;)
+ (NSString * _Nonnull)nibName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull reuseId;)
+ (NSString * _Nonnull)reuseId SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)configureWith:(NSString * _Nullable)title subtitle:(NSString * _Nullable)subtitle activeReportValue:(NSInteger)activeReportValue shouldHideOffset:(BOOL)shouldHideOffset activeReportOffset:(NSInteger)activeReportOffset cellGradient:(AiletGradientColor * _Nonnull)cellGradient;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC10IrLibSwift10Fix_scenes")
@interface Fix_scenes : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift32IRAuthServiceInteractionProvider")
@interface IRAuthServiceInteractionProvider : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class IRSharedUser;
@class IRSharedPortal;
@class NSError;

@interface IRAuthServiceInteractionProvider (SWIFT_EXTENSION(IrLibSwift))
@property (nonatomic, readonly, copy) NSString * _Nonnull authToken;
@property (nonatomic, readonly, copy) NSString * _Nullable domain;
@property (nonatomic, readonly, strong) IRSharedUser * _Nullable user;
- (void)fetchUserPortalsWithLogin:(NSString * _Nonnull)login password:(NSString * _Nonnull)password completion:(void (^ _Nonnull)(NSArray<IRSharedPortal *> * _Nonnull, NSError * _Nullable))completion;
- (void)authorizeOn:(NSString * _Nonnull)domain login:(NSString * _Nonnull)login password:(NSString * _Nonnull)password externalUserId:(NSString * _Nullable)externalUserId completion:(void (^ _Nonnull)(NSString * _Nonnull, NSError * _Nullable))completion;
- (BOOL)isAuthTokenValid SWIFT_WARN_UNUSED_RESULT;
- (void)updateWithShouldUseDevAuthServer:(BOOL)shouldUseDevAuthServer;
- (void)updateWithGuestToken:(NSString * _Nonnull)guestToken;
- (void)updateWithFcmToken:(NSString * _Nullable)fcmToken;
- (BOOL)shouldReauthorizeWithLogin:(NSString * _Nonnull)login password:(NSString * _Nonnull)password externalUserId:(NSString * _Nullable)externalUserId SWIFT_WARN_UNUSED_RESULT;
- (void)resetAccess;
- (void)subscribeToAuthTokenIsInvalid:(void (^ _Nullable)(void))handler;
- (BOOL)shouldUseOnlyOpenIDAuth SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP10IrLibSwift26IRBackgroundEventsDelegate_")
@protocol IRBackgroundEventsDelegate
@property (nonatomic, readonly, copy) void (^ _Nullable backgroundEventsCompletionHandler)(void);
@end

@class IRMultiportalAuthServiceInteractionProvider;
@protocol IRDbConfigProvider;
@class IRTechSupportInteractionProvider;
@class IRVisitServiceInteractionProvider;
@class IRReportsInteractionProvider;
@class IRScreensBuilderInteractionProvider;
@class IRFeatureToggles;
@class IRStoredStateSettings;
@class VisitWidgetReportMatrixDataEntity;
@class UIViewController;
enum IRWorkFlow : NSInteger;

SWIFT_PROTOCOL("_TtP10IrLibSwift21IRDataManagerProtocol_")
@protocol IRDataManagerProtocol
@property (nonatomic, readonly, strong) IRAuthServiceInteractionProvider * _Nonnull auth;
@property (nonatomic, readonly, strong) IRMultiportalAuthServiceInteractionProvider * _Nonnull multiportalAuth;
@property (nonatomic, readonly, strong) id <IRDbConfigProvider> _Nonnull database;
@property (nonatomic, readonly, strong) IRTechSupportInteractionProvider * _Nonnull techSupport;
@property (nonatomic, readonly, strong) IRVisitServiceInteractionProvider * _Nonnull visits;
@property (nonatomic, readonly, strong) IRReportsInteractionProvider * _Nonnull reports;
@property (nonatomic, readonly, strong) IRScreensBuilderInteractionProvider * _Nonnull screens;
@property (nonatomic, readonly, strong) IRFeatureToggles * _Nonnull featureToggles;
@property (nonatomic, readonly, strong) IRStoredStateSettings * _Nonnull storedStateSettings;
- (void)startAnalytics;
- (void)fetchSettingsAndRoutesWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (VisitWidgetReportMatrixDataEntity * _Nullable)defaultReportMatrixWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (void)restartSendingNotSentDataOnUpdate:(void (^ _Nullable)(NSError * _Nullable))onUpdate;
- (NSString * _Nullable)internalTaskIdWithExternalVisitId:(NSString * _Nonnull)externalVisitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (void)logScreenTimeEventWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name duration:(NSInteger)duration;
- (void)restartLocationService;
- (void)showFillReasonsAlertOn:(UIViewController * _Nonnull)vc onAgree:(void (^ _Nullable)(void))onAgree;
- (BOOL)isConnectionAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowDebugFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)updateShowDebugFeaturesTo:(BOOL)shouldShow;
- (void)fetchCatalogsWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (BOOL)shouldFillAbsenceReasonsWithExternalVisitId:(NSString * _Nonnull)externalVisitId SWIFT_WARN_UNUSED_RESULT;
- (enum IRWorkFlow)workflow SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)installId SWIFT_WARN_UNUSED_RESULT;
@end

@class VisitWidgetReportDataEntity;
@protocol ImageResizer;

SWIFT_CLASS("_TtC10IrLibSwift13IRDataManager")
@interface IRDataManager : NSObject <IRDataManagerProtocol>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) IRDataManager * _Nonnull shared;)
+ (IRDataManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) IRTechSupportInteractionProvider * _Nonnull techSupport;
@property (nonatomic, readonly, strong) IRVisitServiceInteractionProvider * _Nonnull visits;
@property (nonatomic, readonly, strong) IRReportsInteractionProvider * _Nonnull reports;
@property (nonatomic, readonly, strong) IRStoredStateSettings * _Nonnull storedStateSettings;
@property (nonatomic, readonly, strong) IRAuthServiceInteractionProvider * _Nonnull auth;
@property (nonatomic, readonly, strong) IRMultiportalAuthServiceInteractionProvider * _Nonnull multiportalAuth;
@property (nonatomic, readonly, strong) id <IRDbConfigProvider> _Nonnull database;
@property (nonatomic, readonly, strong) IRScreensBuilderInteractionProvider * _Nonnull screens;
@property (nonatomic, readonly, strong) IRFeatureToggles * _Nonnull featureToggles;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)updateAppInfoWithIsApp:(BOOL)isApp;
+ (void)updateDeeplinkInfoWithIsStartedViaDeeplink:(BOOL)isStartedViaDeeplink;
- (void)startAnalytics;
- (void)startConnectionMonitoring;
- (void)fetchStoresWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchSettingsAndRoutesWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)restartSendingNotSentDataOnUpdate:(void (^ _Nullable)(NSError * _Nullable))onUpdate;
- (BOOL)canDoRecognitionResultWithPhotoId:(NSString * _Nonnull)photoId SWIFT_WARN_UNUSED_RESULT;
/// Обновление выбранной торговой точки. Используется в случае работы с либой / через диплинки.
/// \param storeId идентификатор торговой точки
///
- (void)updateCurrentStoreWithStoreId:(NSInteger)storeId externalStoreId:(NSString * _Nullable)externalStoreId;
- (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)updateExternalDataWithVisitId:(NSString * _Nonnull)visitId;
+ (void)clearExternalData;
- (void)fetchWidgetsWithVisitId:(NSString * _Nonnull)visitId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSArray<VisitWidgetReportDataEntity *> * _Nonnull)widgetReportsForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetReportDataEntity * _Nullable)widgetReportForVisitWithVisitId:(NSString * _Nonnull)visitId widgetType:(NSString * _Nonnull)widgetType matrixType:(NSString * _Nonnull)matrixType taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (VisitWidgetReportMatrixDataEntity * _Nullable)defaultReportMatrixWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (void)fetchSegmentsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchTasksWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (NSInteger)cachedTasksCount SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)storesCount SWIFT_WARN_UNUSED_RESULT;
- (void)fetchVisitsPlansAndFactsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)updatePhotoResultIntervals:(NSArray<NSNumber *> * _Nonnull)intervals;
- (NSString * _Nullable)internalTaskIdWithExternalVisitId:(NSString * _Nonnull)externalVisitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (void)logScreenTimeEventWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name duration:(NSInteger)duration;
- (NSDictionary<NSString *, id> * _Nonnull)visitStatsWithVisitId:(NSString * _Nonnull)visitId photoId:(NSString * _Nullable)photoId SWIFT_WARN_UNUSED_RESULT;
/// Перезапуск сервиса получения геопопозиции (для выхода из фона)
- (void)restartLocationService;
- (id <ImageResizer> _Nonnull)imageResizerWith:(CGFloat)compressionQuality SWIFT_WARN_UNUSED_RESULT;
- (void)showFillReasonsAlertOn:(UIViewController * _Nonnull)vc onAgree:(void (^ _Nullable)(void))agreeHandler;
- (BOOL)isConnectionAvailable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowDebugFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)updateShowDebugFeaturesTo:(BOOL)shouldShow;
- (void)fetchCatalogsWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (BOOL)shouldFillAbsenceReasonsWithExternalVisitId:(NSString * _Nonnull)externalVisitId SWIFT_WARN_UNUSED_RESULT;
- (enum IRWorkFlow)workflow SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)installId SWIFT_WARN_UNUSED_RESULT;
@end



@class RLMRealmConfiguration;

SWIFT_PROTOCOL("_TtP10IrLibSwift18IRDbConfigProvider_")
@protocol IRDbConfigProvider
@property (nonatomic, readonly) NSInteger dbVersion;
- (RLMRealmConfiguration * _Nonnull)realmConfigWithShouldUseCommonCopy:(BOOL)shouldUseCommonCopy SWIFT_WARN_UNUSED_RESULT;
@end

/// Error thrown by IRInteractManager.
typedef SWIFT_ENUM(NSInteger, IRError, open) {
/// IrLibSwift is in the process of downloading or uploading critical data.
/// Try to repeat the method call later.
/// Code: 0
  IRErrorBusy = 0,
/// An unknown error occurred.
/// Code: 5
  IRErrorUnknown = 5,
/// IrLibSwift detected a lack of internet connection and couldn’t process data.
/// Handle the internet connection and call the method again once it is available.
/// Code: 6
  IRErrorNoConnection = 6,
/// IrLibSwift couldn’t download critically important catalogs.
/// Try to call the <code>setup</code> method with the same data again to trigger catalogs download again.
/// Code: 9
  IRErrorCatalogsError = 9,
/// The authorization token is invalid.
/// Try to call the <code>setup</code> method with the same data again.
/// Code: 7
  IRErrorTokenError = 7,
/// IrLibSwift couldn’t find the input store ID in the local database.
/// Make sure you pass a correct parameter.
/// Code: 10
  IRErrorIncorrectStoreId = 10,
/// IrLibSwift couldn’t find the input visit ID in the local database.
/// Make sure you pass a correct parameter.
/// Code: 12
  IRErrorIncorrectVisitId = 12,
/// IrLibSwift could not authorize for a project.
/// Make sure you pass correct parameters and call the <code>setup</code> method again.
/// Code: 13
  IRErrorAuthError = 13,
/// An operation is already in progress.
/// Code: 16
  IRErrorInProgress = 16,
/// You tried to call a method meant for multiportal mode only without activating it in the setup method.
/// Code: 23
  IRErrorNotMultiportalMode = 23,
/// While in multiportal mode, you passed a non-existent portal to IrLibSwift.
/// Code: 24
  IRErrorIncorrectPortal = 24,
/// While in multiportal mode, you didn’t pass any portal to use.
/// Use the method <code>updatePortal</code> to set the active portal.
/// Code: 25
  IRErrorEmptyPortal = 25,
/// IrLibSwift received a server error.
/// Code: 20
  IRErrorServerError = 20,
};
static NSString * _Nonnull const IRErrorDomain = @"IrLibSwift.IRError";


SWIFT_CLASS("_TtC10IrLibSwift16IRFeatureToggles")
@interface IRFeatureToggles : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum IRLocationErrorBlockType : NSInteger;

/// Настройки запретов на съёмку в зависимости от геолокации
SWIFT_CLASS("_TtC10IrLibSwift32IRGeolocationErrorSharedSettings")
@interface IRGeolocationErrorSharedSettings : NSObject
@property (nonatomic) enum IRLocationErrorBlockType type;
@property (nonatomic) NSInteger threshold;
- (nonnull instancetype)initWithType:(enum IRLocationErrorBlockType)type threshold:(NSInteger)threshold OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift19IRGradientDirection")
@interface IRGradientDirection : NSObject
@property (nonatomic, readonly) CGPoint startPoint;
@property (nonatomic, readonly) CGPoint endPoint;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift20IRGradientDirections")
@interface IRGradientDirections : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) IRGradientDirection * _Nonnull topToBottom;)
+ (IRGradientDirection * _Nonnull)topToBottom SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift17IRInteractManager")
@interface IRInteractManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class IRVisitReport;
@class IRReport;

@interface IRInteractManager (SWIFT_EXTENSION(IrLibSwift))
/// This method authorizes user and downloads all initial data required for futher work with IrLibSwift.
/// \param username login (required for authorization)
///
/// \param password password (required for authorization)
///
/// \param guestToken guestToken (required, must be received from company support manager)
///
/// \param externalUserId additional user id, if there are multiple users under one login (optional). Pass nil if you don’t need to use externalUserId.
///
/// \param notification prefix for receiving notifications on photo recognitions updates. Currently this parameter exists only for backward compatibility with legacy classes. Pass <code>nil</code> and use <code>IRNotification</code> class instead for subscption on photo update
///
/// \param domainName if user has multiple projects to log in, you can use this parameter to login on specific project. This doesn’t work with multiportal mode on. Pass <code>nil</code> if you don’t need to use it.
///
/// \param isMultiportal pass <code>true</code> to activate multiportal mode, when IrLibSwift authorizes for every project available for user. Pass <code>false</code> in case you don’t need it.
///
/// \param completion callback function, the method asynchronously returns <code>NSError</code> if authorization or catalogs loading failed, if the methods finishes with success callback will be called with <code>nil</code> error.
///
+ (void)setupWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password guestToken:(NSString * _Nonnull)guestToken externalUserId:(NSString * _Nullable)externalUserId notification:(NSString * _Nullable)notification domainName:(NSString * _Nullable)domainName isMultiportal:(BOOL)isMultiportal completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Presents IrLibSwift camera from passed viewController.
/// \param presentingVC UIViewController to present Camera from
///
/// \param externalStoreId id of store to make shooting for
///
/// \param externalVisitId id of visit to make shooting for. Visit id must be unique for every store and every day of shooting.
///
///
/// throws:
/// throws an error (IRError in Swift, NSError in Obj-c) if something went wrong.
+ (BOOL)startShootingIn:(UIViewController * _Nonnull)presentingVC externalStoreId:(NSString * _Nonnull)externalStoreId externalVisitId:(NSString * _Nonnull)externalVisitId error:(NSError * _Nullable * _Nullable)error;
/// Asynchronously downloads all the data required for summary report and presents UIViewController with the report
/// \param presentingViewController viewController where will be summary report viewController presented on
///
/// \param visitId id of a visit to generate summary report for
///
/// \param completion callback function, the method asynchronously returns <code>NSError</code> if data loading or presentation of viewController was  failed, if the methods finishes with success callback will be called with <code>nil</code> error.
///
+ (void)showSummaryReportIn:(UIViewController * _Nonnull)presentingViewController visitId:(NSString * _Nonnull)visitId completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Returns array with report for every visit existing locally in IrLibSwift.
///
/// returns:
/// array of <code>IRVisitReport</code>
+ (NSArray<IRVisitReport *> * _Nullable)reportsAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Returns report for specific visit existing locally in IrLibSwift.
/// \param visitId id of visit to generate report for
///
///
/// returns:
/// IRReport
+ (IRReport * _Nullable)reportWithVisitId:(NSString * _Nonnull)visitId error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Returns array with report for every visit existing locally in IrLibSwift in array of dictionaries format.
/// important:
/// this method was made for backward compatibility with legacy classes. Using method returning IRReport is prefered.
///
/// returns:
/// Array of dictionaries with reports.
+ (NSArray<NSDictionary<NSString *, id> *> * _Nonnull)reportsDictionary SWIFT_WARN_UNUSED_RESULT;
/// Checks if any data is not uploaded or downloaded and forces to restart all requests.
/// Asynchronously returns error <code>nil</code> when data is finished to sync (if there were no data to sync it also returns nil). Returns NSError if there any errors during synchronization occured.
/// important:
/// this method was made for objc-compatibility. Use the method with Result<Void, IRError> type if use write in Swift.
/// \param completion callback function, the method asynchronously returns <code>Result<Void, IRError></code>.
///
+ (void)syncDataWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Sets active project to work with.
/// important:
/// Only for multiportal mode. IrLibSwift will throw an error if this method is called without activating multiportal mode in <code>setup</code> method.
/// \param portalId root domain. Don’t pass ‘dairy.intrtl.com’, pass ‘dairy’
///
///
/// throws:
/// throws and IRError (or NSError in objC) if portalId is in incorrect format or project with such portalId has not been authorized during <code>setup</code> method.
+ (BOOL)updateActivePortal:(NSString * _Nonnull)portalId error:(NSError * _Nullable * _Nullable)error;
/// Returns IrLibSwift version number
///
/// returns:
/// String with version number
+ (NSString * _Nonnull)frameworkVersion SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, IRLocationErrorBlockType, open) {
  IRLocationErrorBlockTypeNone = 0,
  IRLocationErrorBlockTypeFull = 1,
  IRLocationErrorBlockTypePartial = 2,
};


SWIFT_CLASS("_TtC10IrLibSwift43IRMultiportalAuthServiceInteractionProvider")
@interface IRMultiportalAuthServiceInteractionProvider : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class IRSharedAuthorizedPortal;

@interface IRMultiportalAuthServiceInteractionProvider (SWIFT_EXTENSION(IrLibSwift))
@property (nonatomic, readonly) BOOL isMultiportal;
@property (nonatomic, readonly, copy) NSString * _Nonnull activeRootDomain;
- (void)updateWithIsMultiportal:(BOOL)isMultiportal;
- (NSArray<IRSharedAuthorizedPortal *> * _Nonnull)authorizedPortals SWIFT_WARN_UNUSED_RESULT;
- (BOOL)updateActivePortalWithRootDomain:(NSString * _Nonnull)rootDomain error:(NSError * _Nullable * _Nullable)error;
- (void)authorizeOnAllAvailablePortalsWithLogin:(NSString * _Nonnull)login password:(NSString * _Nonnull)password externalUserId:(NSString * _Nullable)externalUserId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC10IrLibSwift14IRNotification")
@interface IRNotification : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull photoRecognizedNotification;)
+ (NSNotificationName _Nonnull)photoRecognizedNotification SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull authErrorNotification;)
+ (NSNotificationName _Nonnull)authErrorNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IRPhotoApproveMode, open) {
  IRPhotoApproveModeManual = 0,
  IRPhotoApproveModeAutomatic = 1,
};


/// A class representing a detailed report for a visit, containing various statistics, specific reports metrics (SOS, OSA), and results.
SWIFT_CLASS("_TtC10IrLibSwift8IRReport")
@interface IRReport : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift15IRReportFilters")
@interface IRReportFilters : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull visitId;
@property (nonatomic, readonly) NSInteger storeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull storeName;
@property (nonatomic, readonly, copy) NSString * _Nullable taskId;
@property (nonatomic, readonly, copy) NSString * _Nullable matrixId;
@property (nonatomic, readonly, copy) NSString * _Nullable matrixName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// OSA metric detailed data
SWIFT_CLASS("_TtC10IrLibSwift18IRReportOSADetails")
@interface IRReportOSADetails : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the perfect store metric details within a report.
SWIFT_CLASS("_TtC10IrLibSwift20IRReportPerfectStore")
@interface IRReportPerfectStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing a task within the perfect store metric in a report.
SWIFT_CLASS("_TtC10IrLibSwift24IRReportPerfectStoreTask")
@interface IRReportPerfectStoreTask : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing a KPI within a perfect store task in a report.
SWIFT_CLASS("_TtC10IrLibSwift27IRReportPerfectStoreTaskKPI")
@interface IRReportPerfectStoreTaskKPI : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing a question within a perfect store task in a report.
SWIFT_CLASS("_TtC10IrLibSwift32IRReportPerfectStoreTaskQuestion")
@interface IRReportPerfectStoreTaskQuestion : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing an answer to a question within a perfect store task in a report.
SWIFT_CLASS("_TtC10IrLibSwift38IRReportPerfectStoreTaskQuestionAnswer")
@interface IRReportPerfectStoreTaskQuestionAnswer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the photo details within a report.
SWIFT_CLASS("_TtC10IrLibSwift13IRReportPhoto")
@interface IRReportPhoto : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the error details associated with a photo in the report.
SWIFT_CLASS("_TtC10IrLibSwift18IRReportPhotoError")
@interface IRReportPhotoError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the details of product found within a photo in the report.
SWIFT_CLASS("_TtC10IrLibSwift20IRReportPhotoProduct")
@interface IRReportPhotoProduct : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the width of a product.
SWIFT_CLASS("_TtC10IrLibSwift25IRReportPhotoProductWidth")
@interface IRReportPhotoProductWidth : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Price type
typedef SWIFT_ENUM(NSInteger, IRReportPriceType, open) {
  IRReportPriceTypeNormal = 0,
  IRReportPriceTypePromo = 1,
};


/// A class representing summary of a report.
SWIFT_CLASS("_TtC10IrLibSwift14IRReportResult")
@interface IRReportResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// SOS metric detailed data
SWIFT_CLASS("_TtC10IrLibSwift18IRReportShareShelf")
@interface IRReportShareShelf : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the brand details within an SOS report.
SWIFT_CLASS("_TtC10IrLibSwift23IRReportShareShelfBrand")
@interface IRReportShareShelfBrand : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the category details within an SOS report.
SWIFT_CLASS("_TtC10IrLibSwift26IRReportShareShelfCategory")
@interface IRReportShareShelfCategory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the macro category details within an SOS report.
SWIFT_CLASS("_TtC10IrLibSwift31IRReportShareShelfMacroCategory")
@interface IRReportShareShelfMacroCategory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the visit details within an SOS report.
SWIFT_CLASS("_TtC10IrLibSwift23IRReportShareShelfVisit")
@interface IRReportShareShelfVisit : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the photo statistics within a visit report, including counts for various photo states.
SWIFT_CLASS("_TtC10IrLibSwift23IRReportVisitPhotoStats")
@interface IRReportVisitPhotoStats : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the visit statistics within a report, including photo statistics and various photo ID lists.
SWIFT_CLASS("_TtC10IrLibSwift18IRReportVisitStats")
@interface IRReportVisitStats : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing the statistics of needed to be uploaded/downloaded
SWIFT_CLASS("_TtC10IrLibSwift26IRReportVisitStatsNeedSend")
@interface IRReportVisitStatsNeedSend : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift28IRReportsInteractionProvider")
@interface IRReportsInteractionProvider : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface IRReportsInteractionProvider (SWIFT_EXTENSION(IrLibSwift))
- (NSArray<NSDictionary<NSString *, id> *> * _Nonnull)reportsForAllVisits SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)reportWithExternalVisitId:(NSString * _Nonnull)externalVisitId internalTaskId:(NSString * _Nullable)internalTaskId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)additionalStatsFor:(NSString * _Nonnull)externalVisitId internalTaskId:(NSString * _Nullable)internalTaskId SWIFT_WARN_UNUSED_RESULT;
- (AiletUnsentDataCheckResult * _Nonnull)unsentData SWIFT_WARN_UNUSED_RESULT;
- (AiletUnsentDataCheckResult * _Nonnull)unsentDataFor:(NSString * _Nullable)visitId SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)photosCountFor:(NSString * _Nonnull)visitId SWIFT_WARN_UNUSED_RESULT;
@end

@protocol StoreDetailsOutput;
@protocol TaskDetailsModuleOutput;
@protocol WidgetsModuleInput;
@protocol LegacyReportFiltersModuleOutput;
@class UITabBarController;

SWIFT_CLASS("_TtC10IrLibSwift35IRScreensBuilderInteractionProvider")
@interface IRScreensBuilderInteractionProvider : NSObject
/// Method returns UIViewController depending on input parameteres and values persisted in local DB.
/// <ul>
///   <li>
///     If input <code>taskId</code> is not nil and visit with input <code>externalVisitId</code> exists with such task, the method returns Task Details viewController
///   </li>
///   <li>
///     If input <code>taskId</code> is nil and store with input <code>externalStoreId</code> has tasks, the method returns Store details viewController.
///   </li>
///   <li>
///     In any other cases the method returns Camera viewController
///   </li>
/// </ul>
- (UIViewController * _Nullable)startViewControllerWithExternalStoreId:(NSString * _Nonnull)externalStoreId externalVisitId:(NSString * _Nonnull)externalVisitId taskId:(NSString * _Nullable)taskId cameraOutput:(id <CameraModuleOutput> _Nonnull)cameraOutput storeDetailsOutput:(id <StoreDetailsOutput> _Nonnull)storeDetailsOutput error:(NSError * _Nullable * _Nullable)error backButtonHandler:(void (^ _Nullable)(void))backButtonHandler SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)cameraViewControllerWithOutput:(id <CameraModuleOutput> _Nullable)output externalVisitId:(NSString * _Nonnull)externalVisitId taskId:(NSString * _Nullable)taskId externalStoreId:(NSString * _Nonnull)externalStoreId isOpenedViaDeeplinks:(BOOL)isOpenedViaDeeplinks error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)sosReportListControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)sosReportDetailControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nonnull)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)taskDetailsViewControllerWithOutput:(id <TaskDetailsModuleOutput> _Nullable)output externalVisitId:(NSString * _Nonnull)externalVisitId externalStoreId:(NSString * _Nonnull)externalStoreId visitTaskId:(NSString * _Nonnull)visitTaskId error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)summaryReportViewControllerWithExternalVisitId:(NSString * _Nonnull)externalVisitId error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)reportPhotoBrowseViewControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)summaryReportOOSReportViewControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)standaloneOOSReportViewControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)OSAReportViewControllerWithVisitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)searchController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)retailExecutionStoresScreen SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)sfaStoresScreen SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)filterScreenResults SWIFT_WARN_UNUSED_RESULT;
- (id <WidgetsModuleInput> _Nullable)widgetsController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)storeDetailScreenWithOutput:(id <StoreDetailsOutput> _Nonnull)output storeId:(NSInteger)storeId externalVisitId:(NSString * _Nullable)externalVisitId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)visitStatsScreenWithVisitId:(NSString * _Nonnull)visitId SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)reportFiltersScreenWithOutput:(id <LegacyReportFiltersModuleOutput> _Nonnull)output storeId:(NSInteger)storeId visitId:(NSString * _Nonnull)visitId taskId:(NSString * _Nullable)taskId matrixId:(NSString * _Nullable)matrixId currentReportType:(NSString * _Nullable)currentReportType SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)appDocsScreen SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)retailTasksViewController SWIFT_WARN_UNUSED_RESULT;
- (UITabBarController * _Nonnull)tabBarControllerWithSettingsController:(UIViewController * _Nonnull)settingsController SWIFT_WARN_UNUSED_RESULT;
/// Returns UIViewController for workflow stored in settings
/// retailExecution - storesViewController
/// retailTasks - retailsTasksViewController
- (UIViewController * _Nonnull)workflowBasedStartViewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)manageAppDataViewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)debugFeaturesViewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nonnull)supportTabViewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift24IRSharedAuthorizedPortal")
@interface IRSharedAuthorizedPortal : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nullable rootDomain;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift14IRSharedPortal")
@interface IRSharedPortal : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift12IRSharedUser")
@interface IRSharedUser : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable externalId;
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class IRStoredStateSettingsStore;

/// Хранимые настройки текущего состояния - идентификаторы текущего визита, торговой точки и тому подобное.
/// Ojbc-библиотека использует этот класс для получения и обновления актуальных данных.
SWIFT_CLASS("_TtC10IrLibSwift21IRStoredStateSettings")
@interface IRStoredStateSettings : NSObject
@property (nonatomic, readonly, strong) IRStoredStateSettingsStore * _Nullable currentStore;
- (void)clearCurrentVisit;
@property (nonatomic, readonly) BOOL isOfflineModeActive;
- (void)updateCurrentStoreId:(NSInteger)storeId;
- (void)updateCurrentExternalStoreId:(NSString * _Nonnull)externalStoreId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsStore")
@interface IRStoredStateSettingsStore : NSObject
@property (nonatomic, readonly) NSInteger storeId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalStoreId;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift26IRStoredStateSettingsVisit")
@interface IRStoredStateSettingsVisit : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull visitId;
@property (nonatomic, readonly, copy) NSString * _Nullable externalVisitId;
@property (nonatomic, readonly, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nullable externalUserId;
@property (nonatomic, readonly, copy) NSString * _Nonnull startTimestamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift32IRTechSupportInteractionProvider")
@interface IRTechSupportInteractionProvider : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;

@interface IRTechSupportInteractionProvider (SWIFT_EXTENSION(IrLibSwift))
- (void)logoutWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)show;
- (void)updateDeviceToken:(NSData * _Nonnull)deviceToken;
@end


/// A class representing a visit report, containing the visit ID and the associated report.
SWIFT_CLASS("_TtC10IrLibSwift13IRVisitReport")
@interface IRVisitReport : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift33IRVisitServiceInteractionProvider")
@interface IRVisitServiceInteractionProvider : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface IRVisitServiceInteractionProvider (SWIFT_EXTENSION(IrLibSwift))
- (void)fetchPreviousVisitIfNeededWithExternalVisitId:(NSString * _Nonnull)externalVisitId completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end



typedef SWIFT_ENUM(NSInteger, IRWorkFlow, open) {
  IRWorkFlowRetailExecution = 0,
  IRWorkFlowRetailTasks = 1,
  IRWorkFlowSfa = 2,
};


SWIFT_PROTOCOL("_TtP10IrLibSwift12ImageResizer_")
@protocol ImageResizer
- (NSData * _Nonnull)resizeWithPhotoData:(NSData * _Nonnull)photoData downTo:(float)targetLargerSideSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP10IrLibSwift31LegacyReportFiltersModuleOutput_")
@protocol LegacyReportFiltersModuleOutput
- (void)didUpdateFilters:(IRReportFilters * _Nonnull)filters;
@end


SWIFT_CLASS("_TtC10IrLibSwift11MetricsPlan")
@interface MetricsPlan : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end










SWIFT_CLASS("_TtC10IrLibSwift12ProductGroup")
@interface ProductGroup : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




































































SWIFT_CLASS("_TtC10IrLibSwift8RealmInt")
@interface RealmInt : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Класс-обертка над String, чтобы иметь возможность работать с примитивами в Realm.
SWIFT_CLASS("_TtC10IrLibSwift11RealmString")
@interface RealmString : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift33RecognitionResultActualAssortment")
@interface RecognitionResultActualAssortment : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift38RecognitionResultAssortmentAchievement")
@interface RecognitionResultAssortmentAchievement : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift30RecognitionResultOldAssortment") SWIFT_DEPRECATED_MSG("To be deleted very soon")
@interface RecognitionResultOldAssortment : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift25RecognitionResultPriceBox")
@interface RecognitionResultPriceBox : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift26RecognitionResultPriceLink")
@interface RecognitionResultPriceLink : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift29RecognitionResultProductGroup")
@interface RecognitionResultProductGroup : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift26RecognitionResultRealogram")
@interface RecognitionResultRealogram : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultScene")
@interface RecognitionResultScene : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift27RecognitionResultSceneGroup")
@interface RecognitionResultSceneGroup : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultValue")
@interface RecognitionResultValue : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift22RecognitionResultWidth")
@interface RecognitionResultWidth : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift5Route")
@interface Route : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift10RoutePoint")
@interface RoutePoint : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift31SOSReportListCollectionViewCell")
@interface SOSReportListCollectionViewCell : UICollectionViewCell
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
- (void)awakeFromNib;
/// TODO: Сделано для совместимости с легаси отчетами, убрать когда перепишем сводные отчеты
- (void)setupWithMetricData:(VisitWidgetReportDataEntity * _Nullable)metricData;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift5Scene")
@interface Scene : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift11Scene_types")
@interface Scene_types : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift15ScreenTimeEvent")
@interface ScreenTimeEvent : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift7Segment")
@interface Segment : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift10ShadowView")
@interface ShadowView : UIView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC10IrLibSwift5Shelf")
@interface Shelf : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10IrLibSwift7Shelves")
@interface Shelves : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10IrLibSwift18StoreDetailsOutput_")
@protocol StoreDetailsOutput
- (void)didStartVisitForStoreWithId:(NSInteger)storeId;
- (void)didFinishVisitWithStoreId:(NSInteger)storeId;
- (void)didTriggerOpenSupport;
@end


SWIFT_CLASS("_TtC10IrLibSwift14StoreSceneType")
@interface StoreSceneType : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift10TaskAnswer")
@interface TaskAnswer : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift14TaskAttachment")
@interface TaskAttachment : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP10IrLibSwift23TaskDetailsModuleOutput_")
@protocol TaskDetailsModuleOutput
- (void)didTriggerOpenPriceExecutionReportForTaskWithId:(NSString * _Nullable)taskId;
- (void)didTriggerFetchedPerfectStoreShortWidget;
@end


SWIFT_CLASS("_TtC10IrLibSwift7TaskKpi")
@interface TaskKpi : RLMObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class RLMPropertyDescriptor;

SWIFT_CLASS("_TtC10IrLibSwift12TaskQuestion")
@interface TaskQuestion : RLMObject
+ (NSDictionary<NSString *, RLMPropertyDescriptor *> * _Nonnull)linkingObjectsProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
















































/// Задача привязанная. Добавляется в базу в момент создания визита и остается неизменной, даже если задача на сервере обновилась
SWIFT_CLASS("_TtC10IrLibSwift9VisitTask")
@interface VisitTask : RLMObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10IrLibSwift27VisitWidgetReportDataEntity")
@interface VisitWidgetReportDataEntity : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift32VisitWidgetReportDataEntityTotal")
@interface VisitWidgetReportDataEntityTotal : NSObject
@property (nonatomic, readonly) double value;
@property (nonatomic, readonly) double diff;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift33VisitWidgetReportMatrixDataEntity")
@interface VisitWidgetReportMatrixDataEntity : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10IrLibSwift21WidgetsControlManager")
@interface WidgetsControlManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10IrLibSwift18WidgetsModuleInput_")
@protocol WidgetsModuleInput
- (void)load;
- (void)didOpenScreenWithActiveVisit;
- (void)didOpenScreenWithInactiveVisit;
- (void)didLeaveVisitRelatedScreen;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
